language: csharp
solution: BBS.Libraries.sln
install:
  - nuget restore BBS.Libraries.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BBS.Libraries.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTests/BBS.Libraries.UnitTests.General/bin/Release/BBS.Libraries.UnitTests.General.dll
  
  - nuget pack BBS.Libraries.Contracts\BBS.Libraries.Contracts.csproj
  - nuget push BBS.Libraries.Contracts.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Emails\BBS.Libraries.Emails.csproj
  - nuget push BBS.Libraries.Emails.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Enums\BBS.Libraries.Enums.csproj
  - nuget push BBS.Libraries.Enums.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Extensions\BBS.Libraries.Extensions.csproj
  - nuget push BBS.Libraries.Extensions.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.IO\BBS.Libraries.IO.csproj
  - nuget push BBS.Libraries.IO.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Logging\BBS.Libraries.Logging.csproj
  - nuget push BBS.Libraries.Logging.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Logging.AppInsights\BBS.Libraries.Logging.AppInsights.csproj
  - nuget push BBS.Libraries.Logging.AppInsights.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.SQL\BBS.Libraries.SQL.csproj
  - nuget push BBS.Libraries.SQL.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Templating\BBS.Libraries.Templating.csproj
  - nuget push BBS.Libraries.Templating.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Templating.Handlebars\BBS.Libraries.Templating.Handlebars.csproj
  - nuget push BBS.Libraries.Templating.Handlebars.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/

  - nuget pack BBS.Libraries.Templating.Razor\BBS.Libraries.Templating.Razor.csproj
  - nuget push BBS.Libraries.Templating.Razor.1.0.0.0.nupkg -ApiKey $NUGET_API_KEY -Source http://nuget-betabytesoftware.azurewebsites.net/