language: csharp

branches:
  only:
    - master
    - TravisCI

install:
  - nuget restore -source "$Private_Nuget_Server_Repo_URL;https://www.nuget.org/api/v2" -Verbosity quiet

script:
  # Refreshing Version
  - chmod +x ./TravisCIScripts/IncrementVersion.sh
  - ./TravisCIScripts/IncrementVersion.sh

  # Building Project
  - xbuild /p:Configuration=Release ./BBS.Libraries.Contracts/$ProjectName.csproj /p:TargetFrameworkVersion="v4.5" 

after_success:
  # Deploying Nuget
  - chmod +x ./TravisCIScripts/DeployingNuget.sh
  - ./TravisCIScripts/DeployingNuget.sh
