language: csharp
solution: BBS.Libraries.sln
install:
  - nuget restore BBS.Libraries.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BBS.Libraries.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./UnitTests/BBS.Libraries.UnitTests.General/bin/Release/MyProject.Tests.dll