//-----------------------------------------------------------------------
//    MIT License
//
//    Copyright (c) 2016 Betabyte Software
//
//    Permission is hereby granted, free of charge, to any person obtaining a copy
//    of this software and associated documentation files (the "Software"), to deal
//    in the Software without restriction, including without limitation the rights
//    to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
//    copies of the Software, and to permit persons to whom the Software is
//    furnished to do so, subject to the following conditions:
//
//    The above copyright notice and this permission notice shall be included in all
//    copies or substantial portions of the Software.
//
//    THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//    FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
//    AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//    LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
//    OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
//    SOFTWARE.
//-----------------------------------------------------------------------
// <auto-generated />
// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System.Diagnostics;
using System.CodeDom.Compiler;

#region BBS.Libraries.ConsoleAppTests.Emails.T4Files
namespace BBS.Libraries.ConsoleAppTests.Emails
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Files
	{
		[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
		public static partial class Views
		{
			public static readonly string _root = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/";
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class HandleBars
			{
				public static readonly string _root = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/";
				public static readonly string _01_Mhtml_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/01_Mhtml.cshtml";
				public static readonly string _01_PlainText_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/01_PlainText.cshtml";
				public static readonly string _01_Subject_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/HandleBars/01_Subject.cshtml";
			}
			[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
			public static partial class Razor
			{
				public static readonly string _root = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/";
				public static readonly string _01_Mhtml_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/01_Mhtml.cshtml";
				public static readonly string _01_PlainText_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/01_PlainText.cshtml";
				public static readonly string _01_Subject_cshtml = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Razor/01_Subject.cshtml";
			}
			public static readonly string Web_config = "~/BBS.Libraries.ConsoleAppTests.Emails/Views/Web.config";
		}
	  public static string RepositryNamespace = "BBS.Libraries.ConsoleAppTests.Emails";
	  
	}
}
#endregion

#region BBS.Libraries.ConsoleAppTests.Emails.T4Links
namespace BBS.Libraries.ConsoleAppTests.Emails
{
	[GeneratedCode("T4LocalContent", "1.0"), DebuggerNonUserCode]
	public static partial class T4Links
	{
	}
}
#endregion

