language: csharp
solution: $ProjectName.csproj

install:
  - nuget restore -source "$Private_Nuget_Server_Repo_URL;https://www.nuget.org/api/v2" -Verbosity quiet

script:
  # Refreshing Version
  - chmod +x ./Scripts/IncrementVersion.sh
  - ./Scripts/IncrementVersion.sh

  # Building Project
  - xbuild /p:Configuration=Release $ProjectName.csproj /p:TargetFrameworkVersion="v4.5" 

after_success:
  # Deploying Nuget
  - chmod +x ./Scripts/DeployingNuget.sh
  - ./Scripts/DeployingNuget.sh
